//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KUTUPHANE
{
    using System;
    using System.Collections.Generic;
    
    public partial class KITAP
    {
        public int KITAP_REFNO { get; set; }
        public string ADI { get; set; }
        public string ISBN { get; set; }
        public string YAZARI { get; set; }
        public System.DateTime BASIM_TARIHI { get; set; }
        public string YAYIN_EVI { get; set; }
        public string OZET { get; set; }
    }
}
