//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KUTUPHANE
{
    using System;
    using System.Collections.Generic;
    
    public partial class UYE
    {
        public int UYE_REFNO { get; set; }
        public string AD_SOYAD { get; set; }
        public string ADRES { get; set; }
        public string TELEFON { get; set; }
        public string EMAIL { get; set; }
        public System.DateTime EKLEME_TARIHI { get; set; }
        public bool DURUMU { get; set; }
        public string ACIKLAMA { get; set; }
    }
}
